### ISSUE TITLE
Failing to build due to "signature is unknown trust"

### ISSUE THREAD

**Issue by adi-g15** [ODEX-TOS/tos-live#94]
**Describe the bug**
Unable to build iso, as it is failing to synchronise database, and stops building.

**To Reproduce**
1. Go to toslive/
2. `pacman-key --add ../repo/BUILD/KEYRING/tos.gpg`   (I added this as without it, it was showing 'tos: key "9EA9D0021DB050E7B02B3DA5BFC97A55E04565A4" is unknown')
2. Run `./start.sh -awesome`

**Expected behavior**
No error in key verification

**Screenshots**
![image](https://user-images.githubusercontent.com/37269665/118243674-52be8100-b4bc-11eb-9980-7a2411fd0773.png)

**Desktop (please complete the following information):**
 - OS: archlinux-2021.03.01-x86_64 (running in WSL2)
 - Kernel: Linux version 5.10.16.3-microsoft-standard-WSL2

**Additional context**
Part of `pacman-key --list-sigs` output:
![image](https://user-images.githubusercontent.com/37269665/118244709-7afaaf80-b4bd-11eb-8fe5-9daefde29fce.png)

Also, for me, the installer didn't open :-(    [when clicked; in live boot]

**Comment by F0xedb** [comment]
Hi @adi-g15,

Thank you for trying to build the iso.

It looks like you didn't trust the gpg key hence why the build aborts.

To trust the keys you need to do the following:
```bash
gpg --edit-key sign@odex.be
> trust
Please decide how far you trust this user to correctly verify other users' keys
(by looking at passports, checking fingerprints from different sources, etc.)

  1 = I don't know or won't say
  2 = I do NOT trust
  3 = I trust marginally
  4 = I trust fully
  5 = I trust ultimately
  m = back to the main menu
> 4
>save
```

Repeat the above step for both `sign@odex.be` and `tom@odex.be`
Afterwards you should be able to build the iso.

As for the Live iso issue can you post the output of `tos c` ?

**Comment by adi-g15** [comment]
Thanks @F0xedb for the help, I will try it soon, (and also the output of tos c), may not be able to try it today as i have some work.

Will share the details then, though i believe it should fix it now :smiley: 

> Edit: In the live boot (the option without AZERTY)

As for the installer, i tried running calamares (found it by looking up the installer page, so tried running it), **it said "libkpmcore.so.10" not found.** _**This was the actual error**_





> The next errors are likely due to my modifications

**Then this is the part where i just tried creating a link to an existent  libkpmcore.so.11** (thinking it is a newer version and hopefully backward compatible (which it wasn't i think))
![20210515_010345](https://user-images.githubusercontent.com/37269665/118809939-e337ff80-b8c8-11eb-9be7-c89ff60a7049.png)


Now calameres could start though this was the error (**these error likely popped due to me creating that .so.11 link**
![20210515_010444](https://user-images.githubusercontent.com/37269665/118810271-4b86e100-b8c9-11eb-9a96-7fef7f54ec67.png)

These are previous screenshots, I will try again soon (likely by tomorrow)

**Comment by F0xedb** [comment]
Recently libkpmcore has been updated to version 11.
This caused an incompatibility with our calamares build.

A more recent version of the iso (Or package update in the iso) would have fixed the issue.

We now compile calamares against libkpmcore 11.

You can either grab a new iso or update the packages in the iso using `pacman -Syu`

If you have any more issues please let me know!
