### ISSUE TITLE
Move Download Location

### ISSUE THREAD

**Issue by Suleman-Elahi** [ODEX-TOS/tos-live#98]
The download link is not working from where I am(India). Even the website loads so slowly.

![image](https://user-images.githubusercontent.com/24384996/187844638-93b36ff9-ec4e-4c95-9e76-38a0752bb728.png)

I will suggest to move the ISO to Google Drive or Amazon S3(ig it's free for 5GB). There are tools to create direct link from Google Drive. Another free option is GitHub releases(can be think of as a secondary download source). Since the limit is 1GB, so can think of splitting the ISO into 3 or 4 parts using RAR.

**Comment by adi-g15** [comment]
@Suleman-Elahi, I tried and the [download link](https://repo.odex.be/toslive-awesome.iso) is working for me :thinking:, some temporary problem with your wifi/internet might have caused it to fail, among other things. _Mere pe to kaam kar raha hai_ : )

**Comment by Suleman-Elahi** [comment]
Yes it is working now. But that day I tried multiple connections and the speed was so slow. Thanks anyway.
